### ISSUE TITLE
✨ Add transaction icon URLs

### ISSUE THREAD

**Issue by Hona** [up-banking/api#101] opened 2022-02-17 01:42 UTC
Currently displaying transactions in a table is really ugly without the images like in the app.

**Comment by Hona** [comment] 2022-02-17 01:44
For example, we could do a lot nicer than this: 

![image](https://user-images.githubusercontent.com/10430890/154388459-6b8080fa-fd68-4108-9c9d-b084023027c5.png)

**Comment by markbrown4** [comment] 2024-03-19 01:30
Adding as a duplicate of exposing merchant logo https://github.com/up-banking/api/issues/64

**Closed by markbrown4** 2024-03-19 01:30 UTC
Labels: feature request
