### ISSUE TITLE
All transactions missing for a closed Saver

### ISSUE THREAD

**Issue by plewien** [up-banking/api#107] opened 2022-05-22 10:52 UTC
I created a new Saver to check out the Home Saver feature a few months back. Closed my "Savings" Saver and renamed the Home Saver to that same name. Now I can't access any transactions for the closed "Savings" Saver account through the api.

I can see transactions that go to the closed Saver, but nothing showing that the transaction has been received. Likewise, "Interest" transactions are also missing.

Issue #55 indicates that transactions for closed Savers should normally be visible using [v1/transactions](https://developer.up.com.au/#get_transactions). Has this changed?

**Comment by markbrown4** [comment] 2024-03-20 22:53
> Has this changed?
No changes, transactions on closed savers are not exposed in the API, as in the app.
Only the transactions out of still open accounts are visible(outside of statements).

I'll close this one as a duplicate of https://github.com/up-banking/api/issues/55

**Closed by markbrown4** 2024-03-20 22:53 UTC
