### ISSUE TITLE
BSB/ACC Details Missing from API

### ISSUE THREAD

**Issue by gxander85** [up-banking/api#110] opened 2022-08-03 03:50 UTC
This is something that is desperately needed for a lot of financial institutions processing bank statements digitally. Sometimes without the BSB/ACC exposed within the API, it does not proceed further.
It will show the ACC# as the 37 digit ID and no BSB at all
<img width="427" alt="image" src="https://user-images.githubusercontent.com/19649506/182520114-2dcfc0f3-6c53-46bf-957d-c7060ce3df91.png">
Can we please get the BSB/ACC details added to the Spending Account within the API?

**Comment by markbrown4** [comment] 2024-03-19 01:34
Duplicate of https://github.com/up-banking/api/issues/88

**Closed by markbrown4** 2024-03-19 01:34 UTC
