### ISSUE TITLE
Sending Payments

### ISSUE THREAD

**Issue by sebnil** [up-banking/api#35] opened 2020-08-11 23:35 UTC
I would like to automatically refunda PayId transaction that was made to my account. I suppose this is not possible at the moment. Is this something that you have planned on adding in the future?

**Comment by d11wtq** [comment] 2020-08-11 23:38
Hi @sebnil,

What do you mean by refund? You can't initiate refunds via the app neither. Refunds are generated externally.

We do plan to have the ability to make payments and transfers in the API (with some added safeguards) but not sure this is what you're referring to?

**Comment by sebnil** [comment] 2020-08-12 22:20
Maybe refund is the wrong choice of word. 

When I receive a payment with PayId I would like to in some cases send back the full or a partial amount. If that could be done by simply creating a new transaction in the other direction that would solve the problem. Will that work when you have implemented the additions to the API? My worry from experimenting with the current API is that I can't seem to find a reference to the person sending the money, to be able to send it back.

**Comment by d11wtq** [comment] 2020-08-12 22:25
Gotcha 👍 Currently at this stage payments are completely absent from the API, both in terms of their metadata and in terms of the ability to send them. You'll see payments listed in the list of transactions, but only the basic transaction data. Both the ability to send payments and to get the rich metadata associated with payments will come; we're just not at that stage yet.

**Comment by d11wtq** [comment] 2020-08-13 22:19
Closing as duplicate of https://github.com/up-banking/api/issues/16

**Closed by d11wtq** 2020-08-13 22:19 UTC
Labels: feature request
