### ISSUE TITLE
Initiating transfers out using PayId

### ISSUE THREAD

**Issue by robertmylne** [up-banking/api#83] opened 2021-05-12 06:21 UTC
Does this support the programmatic creation of `PayIds` and well as allow for a transfer out of UPbank via `PayId`?

**Comment by d11wtq** [comment] 2021-05-12 06:56
Hi @robertmylne,

No, sending money via the API is not yet included. Thanks for the interest though!

**Comment by arichtman** [comment] 2023-06-03 03:49
I understand why fully transferring money would be problematic with the api but could we at least initiate payment requests between Up accounts? I'd really like to be able to auto shuffle my money around based on schedules and quotas

**Comment by markbrown4** [comment] 2024-03-19 01:21
Duplicate of https://github.com/up-banking/api/issues/16

**Closed** 2024-03-20 09:39 UTC
Labels: feature request
