### ISSUE TITLE
Personal Access Token allocation not working

### ISSUE THREAD

**Issue by jarradk** [up-banking/api#86] opened 2021-06-06 13:34 UTC
Just tried to collect a new Personal access token, and the browser does not update after scanning the QR code.

Its the same behaviour as this closed issue https://github.com/up-banking/api/issues/81#issue-855231509

Jarrad

**Comment by d11wtq** [comment] 2021-06-06 21:28
Hi @jarradk,

Sorry to hear that. I just had a go and it worked fine for me. Can I ask which browser you're using? Have you tried hard refreshing the browser and trying again (obviously shouldn't be needed, but just to rule it out)?

**Comment by jarradk** [comment] 2021-06-06 23:16
Hi,

Just tried it on windows Chrome Version 91.0.4472.77 (Official Build) (64-bit), with a hard refresh, and also tried incognito mode.

Also tried it a few days ago on another PC with chrome and edge for windows, and also chrome for Debian. 

All outcomes appear the same, it hangs on the https://api.up.com.au/getting_started screen after I've approved the QR code on my phone...I assume its meant to auto-redirect or something similar? This is the first time I am trying to set this up, so I am not exactly sure what to expect...but at this stage it looks like its doing nothing.

**Comment by jradtilbrook** [comment] 2021-06-17 09:04
I'm also experiencing this issue. I've tried over multiple days on Firefox, safari and edge with no success

**Comment by jarradk** [comment] 2021-06-17 09:58
I'm glad you've confirmed I'm not just imagining it - unless we both are!

Are you a 2up user? I am, so I wonder if it's related to issues with that rollout (given 2up isn't fully out yet)?

**Comment by d11wtq** [comment] 2021-06-17 09:59
Are you behind a proxy by any chance? The bit in the middle here is a websocket connection and yeah it should receive a push from the server to tell it to redirect and present the access token. I know we've seen issues caused by corporate proxies in the past.

If you open the Chrome developer tools can you see any JavaScript errors or network errors?

**Comment by jradtilbrook** [comment] 2021-06-17 12:26
@jarradk yes I am a 2up user so perhaps.

I have tried it from my office vpn, phone hotspot and home wifi. Nothing seems to work unfortunately.

There's a few errors in the console:

<img width="741" alt="Screen Shot 2021-06-17 at 20 24 45" src="https://user-images.githubusercontent.com/6128798/122395924-104ffe80-cfaa-11eb-93ee-abf25eaa36ab.png">

**Comment by d11wtq** [comment] 2021-06-17 22:42
That's very useful, thank you. I've passed this info on internally.

**Comment by jarradk** [comment] 2021-06-19 14:11
strange, I see no warnings in my console. I'll try from another PC and my (2up) partners mobile next.

**Comment by nabhanshaaheen** [comment] 2021-06-23 22:43
I'm also having the same issue. Tried on Chrome and Firefox and the same thing was happening.

**Comment by jradtilbrook** [comment] 2021-06-24 00:53
I just realised those errors in the console are actually from extensions. If I load the page without them there are no errors and just the bugsnag message.

I've also restarted my iPhone 12 and deleted and reinstalled the app and it still is not working. Hope that helps

**Comment by jarradk** [comment] 2021-06-24 01:02
> strange, I see no warnings in my console. I'll try from another PC and my (2up) partners mobile next.

No luck using another pc and my partners mobile app. Seems the duck is definitely dead. 😀

**Comment by mickyvx** [comment] 2021-06-25 02:06
I've also attempted this from multiple browsers and not working. Page doesn't refresh or take to the next section to show the access token.

**Comment by NotActuallyTerry** [comment] 2021-06-25 04:51
Edge 91.0.864.54, having the same issue as well.
Looking in dev console shows the websocket connecting fine, with the following messages being passed
![1624596498](https://user-images.githubusercontent.com/670020/123371203-d8e9df00-d5b3-11eb-98be-9e3666982b0e.png)
No new messages are received whenever I scan the QR code on the mobile, and a new challenge code is received every minute without issue.

**Comment by ethanbayliss** [comment] 2021-07-03 13:05
Having the same issue in Edge 91.0.864.59 and Chrome 91.0.4472.124, with and without adblocker enabled. Android phone app.

My friend is also unable to generate a code with his iOS device/Chrome.

Both not 2up users.

@ me if you want me to test anything

**Comment by AussieEevee** [comment] 2021-07-03 23:12
Doing the same to me too. Tried Chrome, Edge, Opera, Firefox... none worked. All are up to date.

**Comment by levibuzolic** [comment] 2021-07-05 06:59
Thanks for all the info everybody.

We haven't been able to replicate this issue locally, but we did notice that after the websocket connection is initialised we were sending through two challenge response keys in quick succession. We're hoping that this is related to the issue that you're all seeing.

@AussieEevee @ethanbayliss @NotActuallyTerry (or anybody else in the thread) would you be able to give it another go and let us know if you see any different behaviour?

If it's stil not working, would you be able to verify if you're seeing a `AUTHORISATION_RESPONSE` message in the websocket messages after scanning the QR code or if you give keep getting the normal `ping` and `CHALLENGE_RESPONSE` messages after scanning.

If everything is working correctly, we'd expect to see something like:

![Pasted_Image_5_7_21__4_57_pm](https://user-images.githubusercontent.com/721323/124430324-60083580-ddb2-11eb-8e0c-2ec1522e4423.png)

**Comment by AussieEevee** [comment] 2021-07-05 07:54
> Thanks for all the info everybody.
> 
> We haven't been able to replicate this issue locally, but we did notice that after the websocket connection is initialised we were sending through two challenge response keys in quick succession. We're hoping that this is related to the issue that you're all seeing.
> 
> @AussieEevee @ethanbayliss @NotActuallyTerry (or anybody else in the thread) would you be able to give it another go and let us know if you see any different behaviour?
> 
> If it's stil not working, would you be able to verify if you're seeing a `AUTHORISATION_RESPONSE` message in the websocket messages after scanning the QR code or if you give keep getting the normal `ping` and `CHALLENGE_RESPONSE` messages after scanning.
> 
> If everything is working correctly, we'd expect to see something like:
> 
> ![Pasted_Image_5_7_21__4_57_pm](https://user-images.githubusercontent.com/721323/124430324-60083580-ddb2-11eb-8e0c-2ec1522e4423.png)

I'm still seeing a lot of pings and challenge responses, but no authorisation response.

![2021-07-05 15_53_03-Up API](https://user-images.githubusercontent.com/26673976/124437112-4c0c0600-dda9-11eb-81b0-3673c55ac0e4.png)

**Comment by ethanbayliss** [comment] 2021-07-05 08:28
![image](https://user-images.githubusercontent.com/8937797/124441050-de160d80-ddad-11eb-936a-25057cc1193d.png)
Hey @levibuzolic, still not working for me - I am available to screenshare on Teams an hour from now if you'd like? 5:30pm AWST

**Comment by lambstrings** [comment] 2021-07-05 08:48
Similar situation here.

![scrot](https://user-images.githubusercontent.com/10214284/124443943-47e9e380-ddbd-11eb-9c59-93bcc71915f3.jpg)

**Comment by levibuzolic** [comment] 2021-07-05 08:54
Thanks @ethanbayliss and @lambstrings - could I grab either of your Upnames and I’ll see what we’re seeing in the logs.

**Comment by ethanbayliss** [comment] 2021-07-05 08:55
> Thanks @ethanbayliss and @lambstrings - could I grab either of your Upnames and I’ll see what we’re seeing in the logs.

$bayliss
I'll trigger another run of it - look for around 4:56-4:59pm AWST

**Comment by lambstrings** [comment] 2021-07-05 08:58
> 
> 
> > Thanks @ethanbayliss and @lambstrings - could I grab either of your Upnames and I’ll see what we’re seeing in the logs.
> 
> $bayliss
> I'll trigger another run of it - look for around 4:56-4:59pm AWST

$samuelmercer

**Comment by GregLahaye** [comment] 2021-07-06 08:04
I'm also having this issue.
If you need any more info to check out in logs, my Upname is $greglahaye, I scanned the code at 4:00 PM AWST today (should be 6pm Melbourne time).

**Comment by tommeier** [comment] 2021-07-07 01:33
hi all, thanks for your patience - we're actively looking at this and you're definitely not forgotten. I believe we have a temporary workaround, the legitimate fix will come soon to follow.

Please change your _in-app_ timezone to Melbourne temporarily -> `Up -> Profile -> Australian Timezone -> Melbourne` - then `Scan QR Code`, can then change back to original timezone.

Proper fix incoming! Apologies its taken a while to narrow down.

**Comment by GregLahaye** [comment] 2021-07-07 01:53
> hi all, thanks for your patience - we're actively looking at this and you're definitely not forgotten. I believe we have a temporary workaround, the legitimate fix will come soon to follow.
> 
> Please change your _in-app_ timezone to Melbourne temporarily -> `Up -> Profile -> Australian Timezone -> Melbourne` - then `Scan QR Code`, can then change back to original timezone.
> 
> Proper fix incoming! Apologies its taken a while to narrow down.

Ah, timezones 😄 Thanks for the fix, can confirm it is working for me!

**Comment by jradtilbrook** [comment] 2021-07-07 02:07
Wow I was looking at everyone posting here and surprised by the number of people having issues posting in AWST 🤔

**Comment by AussieEevee** [comment] 2021-07-07 05:15
> hi all, thanks for your patience - we're actively looking at this and you're definitely not forgotten. I believe we have a temporary workaround, the legitimate fix will come soon to follow.
> 
> Please change your _in-app_ timezone to Melbourne temporarily -> `Up -> Profile -> Australian Timezone -> Melbourne` - then `Scan QR Code`, can then change back to original timezone.
> 
> Proper fix incoming! Apologies its taken a while to narrow down.

That worked. Thank you.

(and yeah, I'm AWST too)

**Comment by tommeier** [comment] 2021-07-12 00:57
Ok all fixed now :) Switching time zones _should_ no longer be necessary - please let me know if it crops up again (or the fix didn't actually work).

**Closed** 2021-07-12 00:59 UTC
Labels: bug
